### ISSUE TITLE
[BUG] Downtime

### ISSUE THREAD

**Issue by alexlostorto** [Nathan13888/VisitorBadgeReloaded#40] opened 2023-07-08 11:36 UTC
**Describe the bug**
The badges return ERROR instead of the actual count. 

![](https://vbr.wocr.tk/badge?page_id=visitor-badge-reloaded-visitors&color=55acb7&style=for-the-badge&logo=Github)

This is fixed when the parameter hit=false.

Why isn't the counter functioning as expected?

**Comment by Nathan13888** [comment] 2023-07-08 18:19
Thanks for the post @alexlostorto.

How did you notice the issue initially? I did some investigation and believe I know the cause of the problem.

**Comment by alexlostorto** [comment] 2023-07-08 18:21
It seems fixed now haha 😂 But did you see the error? I forgot to take a screenshot because I thought it would still be broken 😅

I noticed on my repositories as the badges displayed ERROR rather than the actual count.

**Comment by Nathan13888** [comment] 2023-07-08 18:36
I see, I'm going to be moving the hosting in a few days to another place using Kubernetes. So hopefully I'll have HA and stuff by then.

**Comment by Nathan13888** [comment] 2023-07-08 18:36
I'll close the issue for now, but hopefully the same type of issue doesn't happen again.

**Closed by Nathan13888** 2023-07-08 18:36 UTC
Labels: bug

**Comment by alexlostorto** [comment] 2023-07-08 18:41
Oh so why do you think the problem was caused? And why are you switching to Kubernetes?

**Comment by Nathan13888** [comment] 2023-07-08 19:02
Out of disk space and k8s would offer more redundancy.

**Comment by alexlostorto** [comment] 2023-07-15 15:56
Yep... please fix the issue

![image](https://github.com/Nathan13888/VisitorBadgeReloaded/assets/114829362/7d429985-fcdd-43d0-b413-2ce9ad4bd649)

![image](https://github.com/Nathan13888/VisitorBadgeReloaded/assets/114829362/9c9fcb0c-1a1c-4af9-a861-bc04833986a4)

been like this for 2 days now...

**Comment by Nathan13888** [comment] 2023-07-15 21:02
Ummm guys I'm so sorry this time it crashed because of some obscure bug with CountAPI... I figured out the problem. Hopefully this will be better in the future once I deploy all of this on a Kubernetes cluster...

**Comment by alexlostorto** [comment] 2023-07-15 21:55
You shouldn't even be using CountAPI! I thought you completely migrated away from their unreliable service just a few weeks ago...

**Comment by Nathan13888** [comment] 2023-07-15 23:57
I'm not using it at all anymore but I haven't removed the code and left a flag instead.... But I forgot sometimes the http client could crash my API instead... (Because I set errors to be fatal years ago...)
